# Data files mentioned in the paper
PATH_TO_VIX_DATA = "data_files/VIX_History.csv"
PATH_TO_JAE_DATA = "data_files/Todorov-Zhang-JAE-2021.csv"
PATH_TO_MKT_RF_RET_DATA = "data_files/F-F_Research_Data_Factors_daily.csv"

# Data files generated by ceemdan.py
IMF_DATA_PATHS = {
    "RV": "ceemdan_res/final_imfs_rw_rv.h5",
    "OV": "ceemdan_res/final_imfs_rw_ov.h5",
    "TV": "ceemdan_res/final_imfs_rw_tv.h5",
    "EV": "ceemdan_res/final_imfs_rw_ev.h5",
    "JV": "ceemdan_res/final_imfs_rw_jv.h5",
    "ORV": "ceemdan_res/final_imfs_rw_orv.h5",
}
